# COMMON APPLICATION PROPERTIES

server:
  # The stop processing uses a timeout which provides a grace period during which existing requests 
  # will be allowed to complete but no new requests will be permitted
  shutdown: graceful

# Logging
# logging.level.org.springframework: INFO
logging:
  level:
    org:
      springframework: INFO

# Metrics
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,info'
  info:
    env:
      enabled: true

# Identification
info:
  app:
    name: ${spring.application.name}

# Eureka
eureka:
  client:
    healthcheck:
      enabled: true

#avwx:
#  token: '{cipher}a55eebf22029f129c7aab38026ea536f4b4f2199a1d176215ec81f1b12a791afa4fce34cc08668090688654be307322f968717ec09728e842537f403c05b5b80'
