logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  swagger-ui:
    path: /api/doc

srv-worker:
  http-client:
    read-timeout: 3000
    write-timeout: 3000
    connect-timeout: 3000
    response-timeout: 3000
  retry:
    max-retry: 3
    retry-interval: 3000
  #######################################
  # SRV-WORKER URLs
  url-base: http://localhost:8000/
  url-ping: /ping
  url-load-rdata: /load_rdata
  url-get-geo-supp-files: /get-geo-supp-files
  # END (SRV-WORKER URLs) ###############