spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: api-methyl-it-swagger
        uri: lb://srv-pipeline-runner
        predicates:
          - Path=/api/v1/**
        filters:
          - RewritePath=/api/v1/(?<RID>.*), /api/v1/$\{RID}
      - id: api-methyl-it
        uri: lb://srv-pipeline-runner
        predicates:
          - Path=/api/**
        filters:
          - RewritePath=/api/(?<RID>.*), /api/v1/$\{RID}
      - id: srv-pipeline-runner
        uri: lb://srv-pipeline-runner
        predicates:
        - Path=/runner/**
        filters:
          - StripPrefix=1
      - id: srv-worker
        uri: lb://srv-worker/
        predicates:
        - Path=/worker/**
        filters:
        - StripPrefix=1
      - id: RStudio
        uri: http://srv-worker:8787
        predicates:
          - Path=/rstudio/**
        filters:
          - StripPrefix=1
          #- RewritePath=/rstudio/(?<RID>.*), /$\{RID}
      - id: rstudio-auth-sign-in
        predicates:
          - Path=/auth-sign-in
        uri: http://srv-worker:8787
      - id: rstudio-auth-sign-out
        predicates:
          - Path=/auth-sign-out
        uri: http://srv-worker:8787
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
