spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: srv-pipeline-runner
        uri: lb://srv-pipeline-runner
        predicates:
        - Path=/runner/**
        filters:
          - StripPrefix=1
      - id: srv-worker
        uri: lb://srv-worker/
        predicates:
        - Path=/worker/**
        filters:
        - StripPrefix=1
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
