spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: srv-pipeline-runner
        uri: lb://srv-pipeline-runner
        predicates:
        - Path=/runner/**
        filters:
          - StripPrefix=1
      - id: srv-worker
        uri: lb://srv-worker/
        predicates:
        - Path=/worker/**
        filters:
        - StripPrefix=1
      - id: RStudio
        uri: http://srv-worker:8787
        predicates:
          - Path=/rstudio/**
        filters:
          - StripPrefix=1
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
